TH1D* h2 = new TH1D("cat_muq", ";;", 15, 0, 15)
int N;
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (nbjets == 1) && (njets == 3) ")
h2->SetBinContent(0,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (nbjets == 1) && (njets == 4) ")
h2->SetBinContent(1,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (nbjets == 1) && (njets == 5) ")
h2->SetBinContent(2,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (nbjets == 1) && (njets > 5) ")
h2->SetBinContent(3,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (nbjets > 1) && (njets == 3) ")
h2->SetBinContent(4,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (nbjets > 1) && (njets == 4) ")
h2->SetBinContent(5,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (nbjets > 1) && (njets == 5) ")
h2->SetBinContent(6,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (nbjets > 1) && (njets > 5) ")
h2->SetBinContent(7,N)                                                                                                                                                           
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (lj_peak_distance < 500) && (nbjets == 1) && (njets == 3) ")
h2->SetBinContent(8,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (lj_peak_distance < 500) && (nbjets == 1) && (njets == 4) ")
h2->SetBinContent(9,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (lj_peak_distance < 500) && (nbjets == 1) && (njets == 5) ")
h2->SetBinContent(10,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (lj_peak_distance < 500) && (nbjets == 1) && (njets > 5) ")
h2->SetBinContent(11,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (lj_peak_distance < 500) && (nbjets > 1) && (njets == 4) ")
h2->SetBinContent(12,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (lj_peak_distance < 500) && (nbjets > 1) && (njets == 5) ")
h2->SetBinContent(13,N)
N = ntuple->Draw("njets", "(met_corrected > 40) && (fabs(leps_ID) == 13) && (lj_peak_distance < 500) && (nbjets > 1) && (njets > 5) ")
h2->SetBinContent(14,N)
h2->Draw()


